version: '3.8'
services:
  pizza-shop:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pizza-shop-warehouse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psw
    ports:
      - "7434:5432"